### ISSUE TITLE
ModuleNotFoundError: No module named 'google.apps'

### ISSUE THREAD

**Issue by CodeWithEhtisham** [NickMol/Django--GoogleMapsApi#1]
![image](https://user-images.githubusercontent.com/55108404/201913204-bb33d74f-6cdd-49a4-8139-324315899712.png)

HI i am working on the same project and I want to modify your repository but I am a little bit confused about setting the file you **INSTALLED_APPS** like google.apps.GoogleConfig but this file I did not find any where can you help me to solve this?

and I face another issue on **ROOT_URLCONF** when I comment on these two lines.

**Comment by NickMol** [comment]
Hi!

Google is the name of my Django app. It's not a specific package you need to install.

I can imagine that your app is called something else, so you can delete this text from the settings in your case!

Kind regards,
Nick Mol

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________
From: Ehtisham Ahmed ***@***.***>
Sent: Tuesday, November 15, 2022 12:56:44 PM
To: NickMol/Django--GoogleMapsApi ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NickMol/Django--GoogleMapsApi] ModuleNotFoundError: No module named 'google.apps' (Issue #1)


[image]<https://user-images.githubusercontent.com/55108404/201913204-bb33d74f-6cdd-49a4-8139-324315899712.png>

HI i am working on the same project and I want to modify your repository but I am a little bit confused about setting the file you INSTALLED_APPS like google.apps.GoogleConfig but this file I did not find any where can you help me to solve this?

and I face another issue on ROOT_URLCONF when I comment on these two lines.

**Comment by CodeWithEhtisham** [comment]
yeah, I know but I am using your code I clone the project and set the google map  **api_key** then run the code but face these issues.

**Comment by NickMol** [comment]
I just added a requirements.txt file to the project. Please try to install the packages with: pip install requirements.txt

________________________________
Van: Ehtisham Ahmed ***@***.***>
Verzonden: dinsdag 15 november 2022 18:25
Aan: NickMol/Django--GoogleMapsApi ***@***.***>
CC: NickMol ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [NickMol/Django--GoogleMapsApi] ModuleNotFoundError: No module named 'google.apps' (Issue #1)


yeah, I know but I am using your code I clone the project and set the google map api_key then run the code but face these issues.

**Comment by CodeWithEhtisham** [comment]
I installed the complete requirements but the problem remains the same **ModuleNotFoundError: No module named 'google.apps'** I think you miss something when you push your code into the repo. why you are using **'google.apps.GoogleConfig'** this into Installed_app instead of using just **'google'**

**Comment by NickMol** [comment]
I have added instructions in the Readme file. If I replicate the instructions it works for me. Hope this helps.

Kind regards,
Nick Mol
________________________________
Van: Ehtisham Ahmed ***@***.***>
Verzonden: woensdag 16 november 2022 06:43
Aan: NickMol/Django--GoogleMapsApi ***@***.***>
CC: NickMol ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [NickMol/Django--GoogleMapsApi] ModuleNotFoundError: No module named 'google.apps' (Issue #1)


I installed the complete requirements but the problem remains the same ModuleNotFoundError: No module named 'google.apps' I think you miss something when you push your code into the repo. why you are using 'google.apps.GoogleConfig' this into Installed_app instead of using just 'google'

**Comment by CodeWithEhtisham** [comment]
thank you.
